[tools]
amazon-ecr-credential-helper = "latest"
argocd = "latest"
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
colima = "latest"
"conda:pv" = "latest"
delta = "latest"
direnv = "latest"
docker-cli = "latest"
duckdb = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fx = "latest"
fzf = "latest"
gam = "latest"
gcloud = "latest"
gh = "latest"
"github:BRO3886/gtasks" = "latest"
"github:asciinema/agg" = "latest"
"github:asciinema/asciinema" = "latest"
"github:planetscale/cli" = "latest"
"github:yshavit/mdq" = "latest"
glow = "latest"
go = "latest"
"go:github.com/walles/moar" = "latest"
grpcurl = "latest"
helm = "latest"
helm-ls = "latest"
jq = "latest"
kind = "latest"
kubectl = "latest"
kustomize = "latest"
lazydocker = "latest"
lazygit = "latest"
lima = "latest"
neovim = "latest"
node = "24"
opentofu = "latest"
"pipx:csvkit" = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
zoxide = "latest"

[settings]
experimental = true
